'use strict';

/**
 * Verifies existing-repo automatic NORTH_STAR drafting: snapshot → OpenAI-compatible
 * chat/completions → markdown + extracted PRD fields (same path as enrichExistingRepoQuick).
 * Run: node test/north-star-existing-repo.test.js
 */

const assert = require('assert');
const http = require('http');
const setupMain = require('../setup.js');
const { generateNorthStarFromExistingRepo } = setupMain.hexcurseInstallTestHooks;

/** Valid North Star body (>200 chars, required ## sections). */
const FIXTURE_MARKDOWN = `# North Star

**Project:** FixtureApp

## Vision
Maintain a governed codebase with HexCurse (test fixture).

## Inferred stack
Node.js and TypeScript (inferred from snapshot).

## Key modules and layout
- \`src/index.ts\` — application entry (inferred)
- \`package.json\` — dependencies (inferred)

## Suggested first tasks for Taskmaster
1. Run the automated NORTH_STAR test in CI.
2. Align Taskmaster tasks with repo layout.
3. Document deployment assumptions.

## Out of scope
Third-party billing integrations (TBD).

## Definition of done
HEXCURSE/NORTH_STAR.md reflects the repo; parse-prd succeeds.

## Notes
Generated by mock OpenAI-compatible server for installer tests.
`;

function startMockChatCompletionsServer(responseText) {
  return new Promise((resolve, reject) => {
    const server = http.createServer((req, res) => {
      if (req.method !== 'POST' || !req.url.startsWith('/v1/chat/completions')) {
        res.writeHead(404);
        res.end();
        return;
      }
      let body = '';
      req.on('data', (c) => {
        body += c;
      });
      req.on('end', () => {
        const payload = {
          choices: [
            {
              message: {
                content: responseText,
              },
            },
          ],
        };
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify(payload));
      });
    });
    server.on('error', reject);
    server.listen(0, '127.0.0.1', () => {
      const addr = server.address();
      resolve({ server, port: addr.port });
    });
  });
}

async function testFullNorthStarFromMockLlm() {
  const { server, port } = await startMockChatCompletionsServer(FIXTURE_MARKDOWN);
  try {
    const draft = await generateNorthStarFromExistingRepo({
      provider: 'lmstudio',
      taskmasterEnv: {
        OPENAI_API_KEY: 'test-key',
        OPENAI_BASE_URL: `http://127.0.0.1:${port}/v1`,
      },
      snapshot: 'file src/index.ts\nexport function main() {}\n',
      humanFocus: '',
      projectName: 'FixtureApp',
    });
    assert.ok(draft.northStarMd.includes('# North Star'), 'output has North Star heading');
    assert.ok(draft.northStarMd.includes('## Vision'), 'output has Vision section');
    assert.ok(draft.purpose.length > 10, 'purpose extracted');
    assert.ok(draft.stack.includes('Node'), 'stack extracted');
    assert.ok(draft.modules.includes('index'), 'modules extracted');
    assert.ok(draft.outOfScope.length > 5, 'outOfScope extracted');
    assert.ok(draft.dod.length > 5, 'dod extracted');
  } finally {
    await new Promise((r) => server.close(r));
  }
}

/** Model omits top-level # North Star — installer must prepend (same as production path). */
async function testPrependsNorthStarHeadingWhenMissing() {
  const bodyNoH1 = FIXTURE_MARKDOWN.replace(/^#\s+North Star\s*\n+/im, '');
  assert.ok(!/^#\s+North\s+Star/im.test(bodyNoH1), 'fixture should lack h1 for this test');
  const { server, port } = await startMockChatCompletionsServer(bodyNoH1);
  try {
    const draft = await generateNorthStarFromExistingRepo({
      provider: 'lmstudio',
      taskmasterEnv: {
        OPENAI_API_KEY: 'test-key',
        OPENAI_BASE_URL: `http://127.0.0.1:${port}/v1`,
      },
      snapshot: 'x'.repeat(100),
      humanFocus: '',
      projectName: 'NoH1App',
    });
    assert.ok(/^#\s+North\s+Star/im.test(draft.northStarMd), 'prepended # North Star');
    assert.ok(draft.northStarMd.includes('## Vision'), 'sections preserved');
  } finally {
    await new Promise((r) => server.close(r));
  }
}

async function run() {
  await testFullNorthStarFromMockLlm();
  await testPrependsNorthStarHeadingWhenMissing();
  console.log('north-star-existing-repo.test.js: all tests passed');
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
